data:
  batch_size: 256
  image_size: 64
  data_augmentation:
  - noise
  - rotation
  - flip_hor
  - flip_ver
  - blur
datamodule:
  num_workers: 2
  persistent_workers: true
  pin_memory: false
loss:
  loss: CrossEntropyLoss
  reduction: sum
scheduler:
  T_max: 100
  total_steps: 50
optimizer:
  name: AdamW
  lr: 0.0004
  weight_decay: 0.001
model:
  num_layers: 2
server:
  repo_root: /mnt/calc/lizzzafomenko/aim
  data_root: /mnt/calc/lizzzafomenko/aim/tiny-imagenet-200
seed: 57
model_dir: results/ANSWER
epoch_num: 50
device: 0
logger:
  project: aim_imagenet_classification
  log_model: all
  name: ANSWER
